/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.gx2.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SolicitacaoServico service. Represents a row in the &quot;Ccorp_SolicitacaoServico&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.gx2.model.impl.SolicitacaoServicoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.gx2.model.impl.SolicitacaoServicoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SolicitacaoServico
 * @generated
 */
@ProviderType
public interface SolicitacaoServicoModel extends BaseModel<SolicitacaoServico> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a solicitacao servico model instance should use the {@link SolicitacaoServico} interface instead.
	 */

	/**
	 * Returns the primary key of this solicitacao servico.
	 *
	 * @return the primary key of this solicitacao servico
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this solicitacao servico.
	 *
	 * @param primaryKey the primary key of this solicitacao servico
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this solicitacao servico.
	 *
	 * @return the uuid of this solicitacao servico
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this solicitacao servico.
	 *
	 * @param uuid the uuid of this solicitacao servico
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the solicitacao ID of this solicitacao servico.
	 *
	 * @return the solicitacao ID of this solicitacao servico
	 */
	public long getSolicitacaoId();

	/**
	 * Sets the solicitacao ID of this solicitacao servico.
	 *
	 * @param solicitacaoId the solicitacao ID of this solicitacao servico
	 */
	public void setSolicitacaoId(long solicitacaoId);

	/**
	 * Returns the codigo unimed of this solicitacao servico.
	 *
	 * @return the codigo unimed of this solicitacao servico
	 */
	@AutoEscape
	public String getCodigoUnimed();

	/**
	 * Sets the codigo unimed of this solicitacao servico.
	 *
	 * @param codigoUnimed the codigo unimed of this solicitacao servico
	 */
	public void setCodigoUnimed(String codigoUnimed);

	/**
	 * Returns the descricao of this solicitacao servico.
	 *
	 * @return the descricao of this solicitacao servico
	 */
	@AutoEscape
	public String getDescricao();

	/**
	 * Sets the descricao of this solicitacao servico.
	 *
	 * @param descricao the descricao of this solicitacao servico
	 */
	public void setDescricao(String descricao);

	/**
	 * Returns the data solicitacao of this solicitacao servico.
	 *
	 * @return the data solicitacao of this solicitacao servico
	 */
	public Date getDataSolicitacao();

	/**
	 * Sets the data solicitacao of this solicitacao servico.
	 *
	 * @param dataSolicitacao the data solicitacao of this solicitacao servico
	 */
	public void setDataSolicitacao(Date dataSolicitacao);

	/**
	 * Returns the status of this solicitacao servico.
	 *
	 * @return the status of this solicitacao servico
	 */
	public int getStatus();

	/**
	 * Sets the status of this solicitacao servico.
	 *
	 * @param status the status of this solicitacao servico
	 */
	public void setStatus(int status);

	/**
	 * Returns the prioridade of this solicitacao servico.
	 *
	 * @return the prioridade of this solicitacao servico
	 */
	public int getPrioridade();

	/**
	 * Sets the prioridade of this solicitacao servico.
	 *
	 * @param prioridade the prioridade of this solicitacao servico
	 */
	public void setPrioridade(int prioridade);

	/**
	 * Returns the cliente pj ID of this solicitacao servico.
	 *
	 * @return the cliente pj ID of this solicitacao servico
	 */
	public long getClientePJId();

	/**
	 * Sets the cliente pj ID of this solicitacao servico.
	 *
	 * @param clientePJId the cliente pj ID of this solicitacao servico
	 */
	public void setClientePJId(long clientePJId);

	@Override
	public SolicitacaoServico cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}