/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.gx2.service.base;

import br.com.gx2.model.Auditoria;
import br.com.gx2.service.AuditoriaService;
import br.com.gx2.service.AuditoriaServiceUtil;
import br.com.gx2.service.persistence.AuditoriaPersistence;
import br.com.gx2.service.persistence.ClientePjPersistence;
import br.com.gx2.service.persistence.SolicitacaoServicoPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the auditoria remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link br.com.gx2.service.impl.AuditoriaServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see br.com.gx2.service.impl.AuditoriaServiceImpl
 * @generated
 */
public abstract class AuditoriaServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, AuditoriaService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AuditoriaService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AuditoriaServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		AuditoriaServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AuditoriaService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		auditoriaService = (AuditoriaService)aopProxy;

		AuditoriaServiceUtil.setService(auditoriaService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AuditoriaService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Auditoria.class;
	}

	protected String getModelClassName() {
		return Auditoria.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = auditoriaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected br.com.gx2.service.AuditoriaLocalService auditoriaLocalService;

	protected AuditoriaService auditoriaService;

	@Reference
	protected AuditoriaPersistence auditoriaPersistence;

	@Reference
	protected ClientePjPersistence clientePjPersistence;

	@Reference
	protected SolicitacaoServicoPersistence solicitacaoServicoPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		AuditoriaServiceBaseImpl.class);

}