/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.gx2.model.impl;

import br.com.gx2.model.Auditoria;
import br.com.gx2.model.AuditoriaModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Auditoria service. Represents a row in the &quot;Ccorp_Auditoria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AuditoriaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditoriaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditoriaImpl
 * @generated
 */
@JSON(strict = true)
public class AuditoriaModelImpl
	extends BaseModelImpl<Auditoria> implements AuditoriaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a auditoria model instance should use the <code>Auditoria</code> interface instead.
	 */
	public static final String TABLE_NAME = "Ccorp_Auditoria";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"auditoriaId", Types.BIGINT},
		{"dataAcao", Types.TIMESTAMP}, {"usuario", Types.VARCHAR},
		{"acao", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("auditoriaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataAcao", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("usuario", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("acao", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Ccorp_Auditoria (uuid_ VARCHAR(75) null,auditoriaId LONG not null primary key,dataAcao DATE null,usuario VARCHAR(75) null,acao VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Ccorp_Auditoria";

	public static final String ORDER_BY_JPQL =
		" ORDER BY auditoria.auditoriaId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Ccorp_Auditoria.auditoriaId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AUDITORIAID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AuditoriaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _auditoriaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAuditoriaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _auditoriaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Auditoria.class;
	}

	@Override
	public String getModelClassName() {
		return Auditoria.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Auditoria, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Auditoria, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Auditoria, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Auditoria)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Auditoria, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Auditoria, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Auditoria)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Auditoria, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Auditoria, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Auditoria, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Auditoria, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Auditoria, Object>>();

			attributeGetterFunctions.put("uuid", Auditoria::getUuid);
			attributeGetterFunctions.put(
				"auditoriaId", Auditoria::getAuditoriaId);
			attributeGetterFunctions.put("dataAcao", Auditoria::getDataAcao);
			attributeGetterFunctions.put("usuario", Auditoria::getUsuario);
			attributeGetterFunctions.put("acao", Auditoria::getAcao);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Auditoria, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Auditoria, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Auditoria, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Auditoria, String>)Auditoria::setUuid);
			attributeSetterBiConsumers.put(
				"auditoriaId",
				(BiConsumer<Auditoria, Long>)Auditoria::setAuditoriaId);
			attributeSetterBiConsumers.put(
				"dataAcao",
				(BiConsumer<Auditoria, Date>)Auditoria::setDataAcao);
			attributeSetterBiConsumers.put(
				"usuario",
				(BiConsumer<Auditoria, String>)Auditoria::setUsuario);
			attributeSetterBiConsumers.put(
				"acao", (BiConsumer<Auditoria, String>)Auditoria::setAcao);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAuditoriaId() {
		return _auditoriaId;
	}

	@Override
	public void setAuditoriaId(long auditoriaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_auditoriaId = auditoriaId;
	}

	@JSON
	@Override
	public Date getDataAcao() {
		return _dataAcao;
	}

	@Override
	public void setDataAcao(Date dataAcao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataAcao = dataAcao;
	}

	@JSON
	@Override
	public String getUsuario() {
		if (_usuario == null) {
			return "";
		}
		else {
			return _usuario;
		}
	}

	@Override
	public void setUsuario(String usuario) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_usuario = usuario;
	}

	@JSON
	@Override
	public String getAcao() {
		if (_acao == null) {
			return "";
		}
		else {
			return _acao;
		}
	}

	@Override
	public void setAcao(String acao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_acao = acao;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Auditoria.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Auditoria toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Auditoria>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AuditoriaImpl auditoriaImpl = new AuditoriaImpl();

		auditoriaImpl.setUuid(getUuid());
		auditoriaImpl.setAuditoriaId(getAuditoriaId());
		auditoriaImpl.setDataAcao(getDataAcao());
		auditoriaImpl.setUsuario(getUsuario());
		auditoriaImpl.setAcao(getAcao());

		auditoriaImpl.resetOriginalValues();

		return auditoriaImpl;
	}

	@Override
	public Auditoria cloneWithOriginalValues() {
		AuditoriaImpl auditoriaImpl = new AuditoriaImpl();

		auditoriaImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		auditoriaImpl.setAuditoriaId(
			this.<Long>getColumnOriginalValue("auditoriaId"));
		auditoriaImpl.setDataAcao(
			this.<Date>getColumnOriginalValue("dataAcao"));
		auditoriaImpl.setUsuario(
			this.<String>getColumnOriginalValue("usuario"));
		auditoriaImpl.setAcao(this.<String>getColumnOriginalValue("acao"));

		return auditoriaImpl;
	}

	@Override
	public int compareTo(Auditoria auditoria) {
		long primaryKey = auditoria.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Auditoria)) {
			return false;
		}

		Auditoria auditoria = (Auditoria)object;

		long primaryKey = auditoria.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Auditoria> toCacheModel() {
		AuditoriaCacheModel auditoriaCacheModel = new AuditoriaCacheModel();

		auditoriaCacheModel.uuid = getUuid();

		String uuid = auditoriaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			auditoriaCacheModel.uuid = null;
		}

		auditoriaCacheModel.auditoriaId = getAuditoriaId();

		Date dataAcao = getDataAcao();

		if (dataAcao != null) {
			auditoriaCacheModel.dataAcao = dataAcao.getTime();
		}
		else {
			auditoriaCacheModel.dataAcao = Long.MIN_VALUE;
		}

		auditoriaCacheModel.usuario = getUsuario();

		String usuario = auditoriaCacheModel.usuario;

		if ((usuario != null) && (usuario.length() == 0)) {
			auditoriaCacheModel.usuario = null;
		}

		auditoriaCacheModel.acao = getAcao();

		String acao = auditoriaCacheModel.acao;

		if ((acao != null) && (acao.length() == 0)) {
			auditoriaCacheModel.acao = null;
		}

		return auditoriaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Auditoria, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Auditoria, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Auditoria, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Auditoria)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Auditoria>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Auditoria.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _auditoriaId;
	private Date _dataAcao;
	private String _usuario;
	private String _acao;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Auditoria, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Auditoria)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("auditoriaId", _auditoriaId);
		_columnOriginalValues.put("dataAcao", _dataAcao);
		_columnOriginalValues.put("usuario", _usuario);
		_columnOriginalValues.put("acao", _acao);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("auditoriaId", 2L);

		columnBitmasks.put("dataAcao", 4L);

		columnBitmasks.put("usuario", 8L);

		columnBitmasks.put("acao", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Auditoria _escapedModel;

}