/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.gx2.model.impl;

import br.com.gx2.model.SolicitacaoServico;
import br.com.gx2.service.SolicitacaoServicoLocalServiceUtil;

/**
 * The extended model base implementation for the SolicitacaoServico service. Represents a row in the &quot;Ccorp_SolicitacaoServico&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SolicitacaoServicoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SolicitacaoServicoImpl
 * @see SolicitacaoServico
 * @generated
 */
public abstract class SolicitacaoServicoBaseImpl
	extends SolicitacaoServicoModelImpl implements SolicitacaoServico {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a solicitacao servico model instance should use the <code>SolicitacaoServico</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SolicitacaoServicoLocalServiceUtil.addSolicitacaoServico(this);
		}
		else {
			SolicitacaoServicoLocalServiceUtil.updateSolicitacaoServico(this);
		}
	}

}